/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVerificationRouteImport } from './routes/_app.verification'
import { Route as AppTraceabilityRouteImport } from './routes/_app.traceability'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRequirementsMatrixRouteImport } from './routes/_app.requirements-matrix'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppNewBreakdownRouteImport } from './routes/_app.new-breakdown'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppHardwareRouteImport } from './routes/_app.hardware'
import { Route as AppComplianceRouteImport } from './routes/_app.compliance'
import { Route as AppClassificationRouteImport } from './routes/_app.classification'
import { Route as AppCapabilitiesRouteImport } from './routes/_app.capabilities'
import { Route as AppBreakdownRouteImport } from './routes/_app.breakdown'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppAgentRunsRouteImport } from './routes/_app.agent-runs'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVerificationRoute = AppVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppRoute,
} as any)
const AppTraceabilityRoute = AppTraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRequirementsMatrixRoute = AppRequirementsMatrixRouteImport.update({
  id: '/requirements-matrix',
  path: '/requirements-matrix',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNewBreakdownRoute = AppNewBreakdownRouteImport.update({
  id: '/new-breakdown',
  path: '/new-breakdown',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppHardwareRoute = AppHardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppClassificationRoute = AppClassificationRouteImport.update({
  id: '/classification',
  path: '/classification',
  getParentRoute: () => AppRoute,
} as any)
const AppCapabilitiesRoute = AppCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => AppRoute,
} as any)
const AppBreakdownRoute = AppBreakdownRouteImport.update({
  id: '/breakdown',
  path: '/breakdown',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRunsRoute = AppAgentRunsRouteImport.update({
  id: '/agent-runs',
  path: '/agent-runs',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agent-runs': typeof AppAgentRunsRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/breakdown': typeof AppBreakdownRoute
  '/capabilities': typeof AppCapabilitiesRoute
  '/classification': typeof AppClassificationRoute
  '/compliance': typeof AppComplianceRoute
  '/hardware': typeof AppHardwareRoute
  '/integrations': typeof AppIntegrationsRoute
  '/new-breakdown': typeof AppNewBreakdownRoute
  '/reports': typeof AppReportsRoute
  '/requirements-matrix': typeof AppRequirementsMatrixRoute
  '/settings': typeof AppSettingsRoute
  '/traceability': typeof AppTraceabilityRoute
  '/verification': typeof AppVerificationRoute
}
export interface FileRoutesByTo {
  '/agent-runs': typeof AppAgentRunsRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/breakdown': typeof AppBreakdownRoute
  '/capabilities': typeof AppCapabilitiesRoute
  '/classification': typeof AppClassificationRoute
  '/compliance': typeof AppComplianceRoute
  '/hardware': typeof AppHardwareRoute
  '/integrations': typeof AppIntegrationsRoute
  '/new-breakdown': typeof AppNewBreakdownRoute
  '/reports': typeof AppReportsRoute
  '/requirements-matrix': typeof AppRequirementsMatrixRoute
  '/settings': typeof AppSettingsRoute
  '/traceability': typeof AppTraceabilityRoute
  '/verification': typeof AppVerificationRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/agent-runs': typeof AppAgentRunsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/breakdown': typeof AppBreakdownRoute
  '/_app/capabilities': typeof AppCapabilitiesRoute
  '/_app/classification': typeof AppClassificationRoute
  '/_app/compliance': typeof AppComplianceRoute
  '/_app/hardware': typeof AppHardwareRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/new-breakdown': typeof AppNewBreakdownRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/requirements-matrix': typeof AppRequirementsMatrixRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/traceability': typeof AppTraceabilityRoute
  '/_app/verification': typeof AppVerificationRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-runs'
    | '/approvals'
    | '/audit'
    | '/breakdown'
    | '/capabilities'
    | '/classification'
    | '/compliance'
    | '/hardware'
    | '/integrations'
    | '/new-breakdown'
    | '/reports'
    | '/requirements-matrix'
    | '/settings'
    | '/traceability'
    | '/verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agent-runs'
    | '/approvals'
    | '/audit'
    | '/breakdown'
    | '/capabilities'
    | '/classification'
    | '/compliance'
    | '/hardware'
    | '/integrations'
    | '/new-breakdown'
    | '/reports'
    | '/requirements-matrix'
    | '/settings'
    | '/traceability'
    | '/verification'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/agent-runs'
    | '/_app/approvals'
    | '/_app/audit'
    | '/_app/breakdown'
    | '/_app/capabilities'
    | '/_app/classification'
    | '/_app/compliance'
    | '/_app/hardware'
    | '/_app/integrations'
    | '/_app/new-breakdown'
    | '/_app/reports'
    | '/_app/requirements-matrix'
    | '/_app/settings'
    | '/_app/traceability'
    | '/_app/verification'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verification': {
      id: '/_app/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AppVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/traceability': {
      id: '/_app/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof AppTraceabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requirements-matrix': {
      id: '/_app/requirements-matrix'
      path: '/requirements-matrix'
      fullPath: '/requirements-matrix'
      preLoaderRoute: typeof AppRequirementsMatrixRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-breakdown': {
      id: '/_app/new-breakdown'
      path: '/new-breakdown'
      fullPath: '/new-breakdown'
      preLoaderRoute: typeof AppNewBreakdownRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hardware': {
      id: '/_app/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof AppHardwareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classification': {
      id: '/_app/classification'
      path: '/classification'
      fullPath: '/classification'
      preLoaderRoute: typeof AppClassificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capabilities': {
      id: '/_app/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof AppCapabilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/breakdown': {
      id: '/_app/breakdown'
      path: '/breakdown'
      fullPath: '/breakdown'
      preLoaderRoute: typeof AppBreakdownRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent-runs': {
      id: '/_app/agent-runs'
      path: '/agent-runs'
      fullPath: '/agent-runs'
      preLoaderRoute: typeof AppAgentRunsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentRunsRoute: typeof AppAgentRunsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBreakdownRoute: typeof AppBreakdownRoute
  AppCapabilitiesRoute: typeof AppCapabilitiesRoute
  AppClassificationRoute: typeof AppClassificationRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppHardwareRoute: typeof AppHardwareRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppNewBreakdownRoute: typeof AppNewBreakdownRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRequirementsMatrixRoute: typeof AppRequirementsMatrixRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTraceabilityRoute: typeof AppTraceabilityRoute
  AppVerificationRoute: typeof AppVerificationRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRunsRoute: AppAgentRunsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppBreakdownRoute: AppBreakdownRoute,
  AppCapabilitiesRoute: AppCapabilitiesRoute,
  AppClassificationRoute: AppClassificationRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppHardwareRoute: AppHardwareRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppNewBreakdownRoute: AppNewBreakdownRoute,
  AppReportsRoute: AppReportsRoute,
  AppRequirementsMatrixRoute: AppRequirementsMatrixRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTraceabilityRoute: AppTraceabilityRoute,
  AppVerificationRoute: AppVerificationRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
